# Generated by Django 4.1.4 on 2022-12-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/avatar/default.png', height_field=720, upload_to='avatar', width_field=720),
        ),
    ]
