# Generated by Django 4.1.4 on 2022-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/avatar/default.png', upload_to='avatar'),
        ),
    ]
