# Generated by Django 4.1.4 on 2022-12-30 19:08

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_comment_video_user_comment_like_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment_like_list',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='video_like_list',
            field=models.JSONField(),
        ),
    ]
