# Generated by Django 4.1.4 on 2023-01-01 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_video_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='file',
            field=models.FileField(default='video/error.mp4', upload_to='video'),
        ),
        migrations.CreateModel(
            name='ExamineList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.video')),
            ],
        ),
    ]
