# Generated by Django 4.1.4 on 2023-01-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_videopage_file_examinelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopage',
            name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='examine',
            field=models.IntegerField(default=0),
        ),
    ]
