# Generated by Django 4.1.4 on 2023-01-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_videopage_file_video_examine'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='temp/wait'),
        ),
    ]
