# Generated by Django 4.1.4 on 2023-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_videopage_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopage',
            name='page_title',
            field=models.CharField(max_length=30),
        ),
    ]
