# Generated by Django 4.1.4 on 2023-01-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_videopage_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover',
            field=models.ImageField(default='cover/default.png', upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='videopage',
            name='video_file',
            field=models.FileField(upload_to='temp/wait/'),
        ),
    ]
