# Generated by Django 4.1.4 on 2023-01-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
    ]
